---
- name: Install Bacula Storage
  yum:
    name: bacula-storage-{{ bacula_storage_version }}

- name: Create backup folder
  file:
    dest: "{{ item.archive_device }}"
    mode: 0700
    owner: bacula
    group: bacula
    setype: bacula_store_t
    state: directory
  loop: "{{ bacula_storage_devices }}"

- name: Configure Bacula Storage
  template:
    src: bacula-sd.conf.j2
    dest: /etc/bacula/bacula-sd.conf
    mode: 0640
    owner: root
    group: root
  notify: restart bacula-storage
